name: tdmpc2-hishinuma
channels:
  - pytorch-nightly
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.6.0.dev20241112
  - pytorch-cuda=12.4
  - torchvision=0.15.2
  - pip:
    - numpy==1.24.4
    - tensordict-nightly==2024.11.14
    - torchrl-nightly==2024.11.14
